### ISSUE TITLE
lit 2.0 support

### ISSUE THREAD

**Issue by evanminto** [popeindustries/lit-html#9]
This package still relies on v1 of Lit, but v2 introduces new directives and parser features. I’m working on a project that uses this package for universal server/browser rendering, but doing so forces me to use an outdated version of Lit, so without updated support I may have to pursue other options.

I imagine the developer was hoping to sunset this project once Lit released first-class SSR support, but that doesn’t seem to be happening anytime soon.

**Comment by popeindustries** [comment]
Hi, sorry for the wait. I just released a first version of the new [`@popeindustries/lit`](https://github.com/popeindustries/lit) project. Take a look, and let me know if it works for you.
